### ISSUE TITLE
Installation 404

### ISSUE THREAD

**Issue by bhushanjawle** [Myagi/react-native-wistia#1]
Hi Alex, 
I have two queries, you mentioned 

> It is easy enough to embed Wistia videos in your React Native app using a standard React Native Webview
I might be missing something as I was able to play Youtube video but could not play Wistia.
If you have a  gist to refer to, can you please share that ?

Now for this module, I am unable to install using command npm install react-native-wistia.
Get following error
"npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/react-native-wistia"
Is there alternative way to install ?
I am building on Ubuntu (16.04) and testing with Genymotion simulator.
Thanks

**Comment by alex-mcleod** [comment]
Hi @bhushanjawle,

To embed using a standard webview, make sure the wistia videos you are trying to play aren't restricted to particular domains. 

For this module, I have now pushed it to the npm registry, so if you run `npm install react-native-wistia` it will work.

**Comment by SHRoberts91** [comment]
Hey @alex-mcleod , you said it was easy enough to embed Wistia videos in your React native app using a standard React Native Webview, could you give an example of that? I want to move onto using your library for wistia videos, but I want to at least get them showing in a standard React Native Webview first.  
Thanks!

**Comment by alex-mcleod** [comment]
@SHRoberts91 you should be able to just add the standard Wistia embed HTML to a regular React Native webview (https://facebook.github.io/react-native/releases/next/docs/webview.html). I haven't tested this, but something like:

```javascript
const EMBED_HTML = '<script src="//fast.wistia.com/embed/medias/some-media-id.jsonp" async></script><script src="//fast.wistia.com/assets/external/E-v1.js" async></script><div class="wistia_embed wistia_async_some-media-id" style="height:360px;width:640px">&nbsp;</div>'

function WistiaVideo() {
    return (
        <Webview source={{html: EMBED_HTML}} />
    );
}
```

**Comment by bhushanjawle** [comment]
Hi @SHRoberts91 Just checking if you managed to get this working in WebView as I was not able to. Maybe I am mission something in Wistia security settings.

**Comment by SHRoberts91** [comment]
hey @bhushanjawle, I got it working in WebView, but I'm not really happy about it. it always goes fullscreen, which I'm fine with, but the fullscreen animation is sometimes clean, but most of the time does a weird animation to go fullscreen. here's my code:


`
renderIFrame() {
    return `<iframe
      frameborder="0"
      class="wistia_embed"
      name="wistia_embed"
      src=**videoUrl, ex. '"https://fast.wistia.com/embed/iframe/nv15nyj4ya"**
      width="${this.state.width}"
      height="100%"
      style="margin: -8;"
    >
    </iframe>`;
  }
`

`
    const updatedSource = {
      html: this.renderIFrame()
    };
    return (
      <WebView
        source={updatedSource}
        allowsInlineMediaPlayback
        scalesPageToFit={false}
        scrollEnabled={false}
      />
    );
`
So there's a few things in there that aren't necessary for wistia, but I have this taking in youtube urls as well.  Let me know if it works out for you, or if you find a better way
